# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "378aa51c41764bc650dacadca3d542bc"
name = "QuickStick: Cart & Buy Now"
handle = "sticky-cart-ext"
application_url = "https://sticky-cart.insanedev.in/customize"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_script_tags,write_app_proxy"

[auth]
redirect_urls = [ "https://sticky-cart.insanedev.in/authenticate" ]

[app_proxy]
url     = "https://sticky-cart.insanedev.in/proxy"
subpath = "sticky-cart-proxy"
prefix  = "apps"
